apiVersion: v1
description: Apache Kafka is publish-subscribe messaging rethought as a distributed
  commit log.
name: kafka
version: 0.0.1
appVersion: 2.3.0
keywords:
  - kafka
  - zookeeper
  - kafka statefulset
home: https://kafka.apache.org/
sources:
  - https://github.com/kubernetes/charts/tree/master/incubator/zookeeper
  - https://github.com/Yolean/kubernetes-kafka
  - https://github.com/simonweng/kafka-docker-image
  - https://github.com/apache/kafka
maintainers:
  - name: sweng
    email: sweng@cloudera.com
  - name: ryannedolan
    email: rdolan@cloudera.com
icon: https://kafka.apache.org/images/logo.png
